language: cpp

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq

install:
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

script:
  - qmake Allproxy.pro
  - make