#!/bin/sh
case $1 in
start)
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to 55
iptables -t nat -A OUTPUT -d 127.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 10.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 172.16.0.0/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 192.168.1.1/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 202.141.80.22/24 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 202.141.81.22/24 -j RETURN
iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8123
iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5228 -j REDIRECT --to 8124
;;
stop)
sudo iptables -t nat -F OUTPUT
;;
esac
exit
