#!/system/bin/sh
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to 42850
iptables -t nat -A OUTPUT -p udp --dport 7707 -j REDIRECT --to 42850
iptables -t nat -A OUTPUT -p udp --dport 7708 -j REDIRECT --to 42850
iptables -t nat -A OUTPUT -p udp --dport 7717 -j REDIRECT --to 42850
iptables -t nat -A OUTPUT -p udp --dport 20560 -j REDIRECT --to 42850

iptables -t nat -A OUTPUT -p tcp -d 172.16.25.74 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 10.42.0.1 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 10.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 172.16.0.0/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 192.168.1.1/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 202.141.80.0/24 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 202.141.80.14 -j RETURN

iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8123
iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 22 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5228 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5223 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5222 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5242 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 4244 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 943 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 28852 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 8075 -j REDIRECT --to 8124
exit
