#!/system/bin/sh
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to 42850
iptables -t nat -A OUTPUT -p tcp -d 172.16.25.74 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 10.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 172.16.0.0/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 192.168.1.1/16 -j RETURN
iptables -t nat -A OUTPUT -p tcp -d 202.141.80.22 -j RETURN
iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8123
iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8124
iptables -t nat -A OUTPUT -p tcp --dport 5228 -j REDIRECT --to 8124
exit
